services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    environment:
      BACKEND_URL: ${BACKEND_URL:-http://host.docker.internal:3000}
      SETTLEMENT_BACKEND_URL: ${SETTLEMENT_BACKEND_URL:-http://host.docker.internal:8000}
    ports:
      - "${PORT:-3005}:80"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./build:/www/data:ro
